import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <meta http-equiv="content-language" content="ja" />
      <meta charSet="utf-8" />
      <body className={"flex flex-col items-center mb-2 bg-[#FCF0DE] mx-2"}>
        {children}
      </body>
    </html>
  );
}
